<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerLzMrmql\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerLzMrmql/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerLzMrmql.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerLzMrmql\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerLzMrmql\App_KernelDevDebugContainer([
    'container.build_hash' => 'LzMrmql',
    'container.build_id' => 'e1e9dc8a',
    'container.build_time' => 1606651690,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerLzMrmql');
