<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    '_preview_error' => [['code', '_format'], ['_controller' => 'error_controller::preview', '_format' => 'html'], ['code' => '\\d+'], [['variable', '.', '[^/]++', '_format', true], ['variable', '/', '\\d+', 'code', true], ['text', '/_error']], [], []],
    'app_task_new' => [[], ['_controller' => 'App\\Controller\\TaskController::new'], [], [['text', '/form']], [], []],
    'task_success' => [[], ['_controller' => 'App\\Controller\\TaskController::successAction'], [], [['text', '/success']], [], []],
    'index' => [[], ['_controller' => 'App\\Controller\\TaskController::new'], [], [['text', '/form']], [], []],
];
